---
swagger: "2.0"
info:
  version: "0.0.1"
  title: "revolution"
  contact:
    url: "https://www.metaswitch.com/"
    email: "api-support@metaswitch.com"
  license:
    name: "Proprietary"
    url: "https://www.metaswitch.com"
basePath: "/revolution/api"
tags:
- name: "revolution"
  description: "revolution"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /all_info/{username}/{password}/{to}:
    get:
      tags:
      - "all"
      summary: "Get all the info"
      operationId: "all_info"
      parameters:
      - name: "username"
        in: "path"
        description: "Username for logging in\n"
        required: true
        type: "string"
      - name: "password"
        in: "path"
        description: "Users password"
        required: true
        type: "string"
      - name: "to"
        in: "path"
        description: "Start or end point"
        required: true
        type: "string"
      responses:
        200:
          description: "Success. We have found the info."
          schema:
            $ref: "#/definitions/allInfo"
      x-swagger-router-controller: "swagger_server.controllers.all_controller"
  /charge_perc/nissan/{username}/{password}:
    get:
      tags:
      - "status"
      summary: "Get the charge percentage"
      operationId: "get_charge_perc"
      parameters:
      - name: "username"
        in: "path"
        description: "Username for logging in\n"
        required: true
        type: "string"
      - name: "password"
        in: "path"
        description: "Users password"
        required: true
        type: "string"
      responses:
        200:
          description: "Success. The battery status has been found."
          schema:
            $ref: "#/definitions/chargePerc"
        400:
          description: "Missing field.  Invalid configuration record."
        404:
          description: "User not found"
      x-swagger-router-controller: "swagger_server.controllers.status_controller"
  /dist_to_charger/{lat_here}/{long_here}/{lat_there}/{long_there}:
    get:
      tags:
      - "dist"
      summary: "Get the distance to charger"
      operationId: "get_dist_to_charger"
      parameters:
      - name: "lat_here"
        in: "path"
        description: "The latitude or longitude"
        required: true
        type: "string"
      - name: "long_here"
        in: "path"
        description: "The latitude or longitude"
        required: true
        type: "string"
      - name: "lat_there"
        in: "path"
        description: "The latitude or longitude"
        required: true
        type: "string"
      - name: "long_there"
        in: "path"
        description: "The latitude or longitude"
        required: true
        type: "string"
      responses:
        200:
          description: "Success. Distance found."
          schema:
            $ref: "#/definitions/distToCharger"
        400:
          description: "Bad request."
      x-swagger-router-controller: "swagger_server.controllers.dist_controller"
  /chargers_on_route/{from}/{to}:
    get:
      tags:
      - "chargers_on_route"
      summary: "Get a list of the chargers on route"
      operationId: "chargers_on_route"
      parameters:
      - name: "from"
        in: "path"
        description: "Start or end point"
        required: true
        type: "string"
      - name: "to"
        in: "path"
        description: "Start or end point"
        required: true
        type: "string"
      responses:
        200:
          description: "Success. Chargers found."
          schema:
            $ref: "#/definitions/onRoute"
        400:
          description: "Bad request."
        404:
          description: "No chargers found!"
      x-swagger-router-controller: "swagger_server.controllers.chargers_on_route_controller"
definitions:
  chargePerc:
    type: "object"
    required:
    - "percentage"
    properties:
      percentage:
        type: "string"
        description: "The percentage of battery."
    example:
      percentage: "percentage"
  distToCharger:
    type: "object"
    required:
    - "dist_km"
    - "dist_miles"
    properties:
      dist_miles:
        type: "string"
        description: "The distance in miles"
      dist_km:
        type: "string"
        description: "The distance in km"
    example:
      dist_miles: "dist_miles"
      dist_km: "dist_km"
  onRoute:
    type: "array"
    items:
      $ref: "#/definitions/charger"
  charger:
    type: "object"
    properties:
      lat:
        type: "string"
        description: "latitude"
      long:
        type: "string"
        description: "longitude"
      network:
        type: "string"
        description: "Network station is on."
      dist_miles:
        type: "string"
        description: "The distance in miles"
      dist_km:
        type: "string"
        description: "The distance in km"
      extra_time:
        type: "string"
        description: "Extra time needed"
      other:
        type: "string"
        description: "Other possible details."
    example:
      other: "other"
      dist_miles: "dist_miles"
      dist_km: "dist_km"
      lat: "lat"
      long: "long"
      network: "network"
      extra_time: "extra_time"
  allInfo:
    type: "object"
    properties:
      car:
        $ref: "#/definitions/allInfo_car"
      chargers:
        type: "array"
        items:
          $ref: "#/definitions/charger"
    example:
      car:
        charge: "charge"
        lat: "lat"
        long: "long"
      chargers:
      - other: "other"
        dist_miles: "dist_miles"
        dist_km: "dist_km"
        lat: "lat"
        long: "long"
        network: "network"
        extra_time: "extra_time"
      - other: "other"
        dist_miles: "dist_miles"
        dist_km: "dist_km"
        lat: "lat"
        long: "long"
        network: "network"
        extra_time: "extra_time"
  allInfo_car:
    properties:
      lat:
        type: "string"
      long:
        type: "string"
      charge:
        type: "string"
        description: "The charge in watt hour"
    example:
      charge: "charge"
      lat: "lat"
      long: "long"
parameters:
  username:
    name: "username"
    in: "path"
    description: "Username for logging in\n"
    required: true
    type: "string"
  password:
    name: "password"
    in: "path"
    description: "Users password"
    required: true
    type: "string"
  latHere:
    name: "lat_here"
    in: "path"
    description: "The latitude or longitude"
    required: true
    type: "string"
  longHere:
    name: "long_here"
    in: "path"
    description: "The latitude or longitude"
    required: true
    type: "string"
  latThere:
    name: "lat_there"
    in: "path"
    description: "The latitude or longitude"
    required: true
    type: "string"
  longThere:
    name: "long_there"
    in: "path"
    description: "The latitude or longitude"
    required: true
    type: "string"
  from:
    name: "from"
    in: "path"
    description: "Start or end point"
    required: true
    type: "string"
  to:
    name: "to"
    in: "path"
    description: "Start or end point"
    required: true
    type: "string"
