# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.all_info_car import AllInfoCar  # noqa: F401,E501
from swagger_server.models.charger import Charger  # noqa: F401,E501
from swagger_server import util


class AllInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, car=None, chargers=None):  # noqa: E501
        """AllInfo - a model defined in Swagger

        :param car: The car of this AllInfo.  # noqa: E501
        :type car: AllInfoCar
        :param chargers: The chargers of this AllInfo.  # noqa: E501
        :type chargers: List[Charger]
        """
        self.swagger_types = {
            'car': AllInfoCar,
            'chargers': List[Charger]
        }

        self.attribute_map = {
            'car': 'car',
            'chargers': 'chargers'
        }

        self._car = car
        self._chargers = chargers

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The allInfo of this AllInfo.  # noqa: E501
        :rtype: AllInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def car(self):
        """Gets the car of this AllInfo.


        :return: The car of this AllInfo.
        :rtype: AllInfoCar
        """
        return self._car

    @car.setter
    def car(self, car):
        """Sets the car of this AllInfo.


        :param car: The car of this AllInfo.
        :type car: AllInfoCar
        """

        self._car = car

    @property
    def chargers(self):
        """Gets the chargers of this AllInfo.


        :return: The chargers of this AllInfo.
        :rtype: List[Charger]
        """
        return self._chargers

    @chargers.setter
    def chargers(self, chargers):
        """Sets the chargers of this AllInfo.


        :param chargers: The chargers of this AllInfo.
        :type chargers: List[Charger]
        """

        self._chargers = chargers
