/**
 * revolution
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: api-support@metaswitch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Revolution) {
      root.Revolution = {};
    }
    root.Revolution.DistToCharger = factory(root.Revolution.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DistToCharger model module.
   * @module model/DistToCharger
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>DistToCharger</code>.
   * @alias module:model/DistToCharger
   * @class
   * @param distMiles {String} The distance in miles
   * @param distKm {String} The distance in km
   */
  var exports = function(distMiles, distKm) {
    var _this = this;

    _this['dist_miles'] = distMiles;
    _this['dist_km'] = distKm;
  };

  /**
   * Constructs a <code>DistToCharger</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DistToCharger} obj Optional instance to populate.
   * @return {module:model/DistToCharger} The populated <code>DistToCharger</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('dist_miles')) {
        obj['dist_miles'] = ApiClient.convertToType(data['dist_miles'], 'String');
      }
      if (data.hasOwnProperty('dist_km')) {
        obj['dist_km'] = ApiClient.convertToType(data['dist_km'], 'String');
      }
    }
    return obj;
  }

  /**
   * The distance in miles
   * @member {String} dist_miles
   */
  exports.prototype['dist_miles'] = undefined;
  /**
   * The distance in km
   * @member {String} dist_km
   */
  exports.prototype['dist_km'] = undefined;



  return exports;
}));


