/**
 * revolution
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: api-support@metaswitch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AllInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/AllInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.Revolution) {
      root.Revolution = {};
    }
    root.Revolution.AllApi = factory(root.Revolution.ApiClient, root.Revolution.AllInfo);
  }
}(this, function(ApiClient, AllInfo) {
  'use strict';

  /**
   * All service.
   * @module api/AllApi
   * @version 0.0.1
   */

  /**
   * Constructs a new AllApi. 
   * @alias module:api/AllApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the allInfo operation.
     * @callback module:api/AllApi~allInfoCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AllInfo} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all the info
     * @param {String} username Username for logging in 
     * @param {String} password Users password
     * @param {String} to Start or end point
     * @param {module:api/AllApi~allInfoCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AllInfo}
     */
    this.allInfo = function(username, password, to, callback) {
      var postBody = null;

      // verify the required parameter 'username' is set
      if (username === undefined || username === null) {
        throw new Error("Missing the required parameter 'username' when calling allInfo");
      }

      // verify the required parameter 'password' is set
      if (password === undefined || password === null) {
        throw new Error("Missing the required parameter 'password' when calling allInfo");
      }

      // verify the required parameter 'to' is set
      if (to === undefined || to === null) {
        throw new Error("Missing the required parameter 'to' when calling allInfo");
      }


      var pathParams = {
        'username': username,
        'password': password,
        'to': to
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = AllInfo;

      return this.apiClient.callApi(
        '/all_info/{username}/{password}/{to}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
