/**
 * revolution
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: api-support@metaswitch.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/OnRoute'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/OnRoute'));
  } else {
    // Browser globals (root is window)
    if (!root.Revolution) {
      root.Revolution = {};
    }
    root.Revolution.ChargersOnRouteApi = factory(root.Revolution.ApiClient, root.Revolution.OnRoute);
  }
}(this, function(ApiClient, OnRoute) {
  'use strict';

  /**
   * ChargersOnRoute service.
   * @module api/ChargersOnRouteApi
   * @version 0.0.1
   */

  /**
   * Constructs a new ChargersOnRouteApi. 
   * @alias module:api/ChargersOnRouteApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the chargersOnRoute operation.
     * @callback module:api/ChargersOnRouteApi~chargersOnRouteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/OnRoute} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a list of the chargers on route
     * @param {String} from Start or end point
     * @param {String} to Start or end point
     * @param {module:api/ChargersOnRouteApi~chargersOnRouteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/OnRoute}
     */
    this.chargersOnRoute = function(from, to, callback) {
      var postBody = null;

      // verify the required parameter 'from' is set
      if (from === undefined || from === null) {
        throw new Error("Missing the required parameter 'from' when calling chargersOnRoute");
      }

      // verify the required parameter 'to' is set
      if (to === undefined || to === null) {
        throw new Error("Missing the required parameter 'to' when calling chargersOnRoute");
      }


      var pathParams = {
        'from': from,
        'to': to
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = OnRoute;

      return this.apiClient.callApi(
        '/chargers_on_route/{from}/{to}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
